minimumReleaseAgeExclude:
  - '@types/node@25.9.0'
  - antd@6.4.3

overrides:
  keyv@6.0.0: 5.6.0
  flat-cache@6.1.24: 6.1.23
  file-entry-cache@11.1.6: 11.1.5
  cacheable-request@13.0.20: 13.0.19
  cacheable@2.5.1: 2.5.0
  '@cacheable/memory@2.2.1': 2.2.0
  cache-manager@7.2.10: 7.2.9
  '@cacheable/node-cache@3.1.2': 3.1.1
  '@cacheable/utils@2.5.1': 2.5.0
  '@cacheable/net@2.1.1': 2.1.0
  ecto@5.0.1: 5.0.0
